import { integer, text } from "drizzle-orm/sqlite-core";

/**
 * Shared column helpers.
 *
 * - IDs are random UUIDs generated by the application (safe for
 *   distributed/serverless inserts and future offline clients).
 * - Instants are stored as INTEGER milliseconds since epoch, UTC.
 *   They are never stored as formatted strings; the UI formats them in
 *   the organization's timezone.
 * - Calendar dates with no time component (birthdays, hire dates) are
 *   stored as ISO `YYYY-MM-DD` text.
 */
export const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

export const utcTimestamp = (name: string) => integer(name, { mode: "timestamp_ms" });

export const createdAt = () =>
  utcTimestamp("created_at")
    .notNull()
    .$defaultFn(() => new Date());

export const updatedAt = () =>
  utcTimestamp("updated_at")
    .notNull()
    .$defaultFn(() => new Date())
    .$onUpdateFn(() => new Date());

export const calendarDate = (name: string) => text(name);
