/**
 * Development seed CLI.
 *
 *   npm run db:seed:local -- --admin-email you@example.com
 *   npm run db:seed:remote -- --admin-email you@example.com --confirm-remote daycare-db
 *
 * Options (flags win over environment variables):
 *   --admin-email  / SEED_ADMIN_EMAIL / AUTH_EMAIL      required — email recorded for the owner user row
 *   --admin-auth-id / SEED_ADMIN_AUTH_ID               auth_provider_id to link as DAYCARE_OWNER
 *                                                      (default "password:usr_bootstrap" = the current password login)
 *   --admin-name   / SEED_ADMIN_NAME / AUTH_USER_NAME  display name (default "Daycare Owner")
 *
 * Environment variables are read from the shell and, if present, from .env.local.
 *   --target local|remote                 default local (the local D1 shared by `npm run dev:vinext` and `npm run gateway:dev`)
 *   --confirm-remote <database_name>      REQUIRED for --target remote; must equal the D1 database name
 *   --out <file>                          only write the SQL file, don't execute it
 *
 * Safety: the seed never runs automatically (not in build, dev or deploy), and
 * running it against a remote database needs the explicit confirmation flag. It
 * only uses INSERT OR IGNORE, so it never deletes or overwrites existing rows.
 */
import { join } from "node:path";
import { arg, executeSqlFile, fail, loadLocalEnv, readTarget, requireRemoteConfirmation, ROOT, writeSqlFile } from "../lib/cli";
import { buildSeed } from "./build-seed";

const DEFAULT_OUT = join(ROOT, "scripts", "seed", "out", "dev-seed.sql");

async function main() {
  loadLocalEnv();
  const target = readTarget();

  const adminEmail = arg("admin-email") || process.env.SEED_ADMIN_EMAIL || process.env.AUTH_EMAIL;
  const adminAuthProviderId = arg("admin-auth-id") || process.env.SEED_ADMIN_AUTH_ID || "password:usr_bootstrap";
  const adminName = (arg("admin-name") || process.env.SEED_ADMIN_NAME || process.env.AUTH_USER_NAME || "Daycare Owner").trim();
  if (!adminEmail || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(adminEmail)) {
    fail("Provide the owner's email: --admin-email you@example.com (or set SEED_ADMIN_EMAIL / AUTH_EMAIL).");
  }
  if (target === "remote") {
    requireRemoteConfirmation("seed sample data", "Only do this for a development/staging database — never for a production tenant database.");
  }

  const [first, ...rest] = adminName.split(/\s+/);
  const seed = await buildSeed({
    adminAuthProviderId,
    adminEmail,
    adminFirstName: first || "Daycare",
    adminLastName: rest.join(" "),
    now: new Date(),
  });

  const outFile = writeSqlFile(arg("out") || DEFAULT_OUT, "Generated by scripts/seed/seed.ts — development sample data only.", seed.statements);
  if (arg("out") !== undefined) return;
  executeSqlFile(target, outFile);

  console.log("\n✔ Seed complete");
  console.table(seed.summary);
  console.log("Demo time-clock PINs (development only):");
  console.table(seed.demoPins);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
