/**
 * Development seed CLI.
 *
 *   npm run db:seed:local -- --admin-email you@example.com
 *   npm run db:seed:remote -- --admin-email you@example.com --confirm-remote daycare-db
 *
 * Options (flags win over environment variables):
 *   --admin-email  / SEED_ADMIN_EMAIL / AUTH_EMAIL      required — email recorded for the owner user row
 *   --admin-auth-id / SEED_ADMIN_AUTH_ID               auth_provider_id to link as DAYCARE_OWNER
 *                                                      (default "password:usr_bootstrap" = the current password login)
 *   --admin-name   / SEED_ADMIN_NAME / AUTH_USER_NAME  display name (default "Daycare Owner")
 *
 * Environment variables are read from the shell and, if present, from .env.local.
 *   --target local|remote                 default local (wrangler's local D1 used by `npm run gateway:dev`)
 *   --confirm-remote <database_name>      REQUIRED for --target remote; must equal the D1 database name
 *   --out <file>                          only write the SQL file, don't execute it
 *
 * Safety: the seed never runs automatically (not in build, dev or deploy), and
 * running it against a remote database needs the explicit confirmation flag. It
 * only uses INSERT OR IGNORE, so it never deletes or overwrites existing rows.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { buildSeed } from "./build-seed";

const ROOT = resolve(__dirname, "..", "..");
const WORKER_DIR = join(ROOT, "cloudflare", "d1-gateway");
const DEFAULT_OUT = join(ROOT, "scripts", "seed", "out", "dev-seed.sql");

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  if (i === -1) return undefined;
  const value = process.argv[i + 1];
  return value && !value.startsWith("--") ? value : "";
}

function quoteWindowsArg(value: string): string {
  if (!/[\s"]/.test(value)) return value;
  return `"${value.replace(/"/g, '\\"')}"`;
}

function fail(message: string): never {
  console.error(`\n✖ ${message}\n`);
  process.exit(1);
}

/** Reads `database_name` from wrangler.jsonc without parsing secrets (there are none in that file). */
function configuredDatabaseName(): string | undefined {
  const text = readFileSync(join(WORKER_DIR, "wrangler.jsonc"), "utf8");
  return /"database_name"\s*:\s*"([^"]+)"/.exec(text)?.[1];
}

async function main() {
  const envFile = join(ROOT, ".env.local");
  if (existsSync(envFile)) {
    try {
      process.loadEnvFile(envFile);
    } catch {
      console.warn("Could not read .env.local — continuing with flags and shell variables only.");
    }
  }

  const target = (arg("target") ?? "local") as "local" | "remote";
  if (target !== "local" && target !== "remote") fail(`--target must be "local" or "remote".`);

  const adminEmail = arg("admin-email") || process.env.SEED_ADMIN_EMAIL || process.env.AUTH_EMAIL;
  const adminAuthProviderId = arg("admin-auth-id") || process.env.SEED_ADMIN_AUTH_ID || "password:usr_bootstrap";
  const adminName = (arg("admin-name") || process.env.SEED_ADMIN_NAME || process.env.AUTH_USER_NAME || "Daycare Owner").trim();
  if (!adminEmail || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(adminEmail)) {
    fail("Provide the owner's email: --admin-email you@example.com (or set SEED_ADMIN_EMAIL / AUTH_EMAIL).");
  }

  if (target === "remote") {
    const dbName = configuredDatabaseName();
    if (!dbName || arg("confirm-remote") !== dbName) {
      fail(
        `Refusing to seed a REMOTE database without confirmation.\n` +
          `  Re-run with: --confirm-remote ${dbName ?? "<database_name>"}\n` +
          `  Only do this for a development/staging database — never for a production tenant database.`,
      );
    }
  }

  const [first, ...rest] = adminName.split(/\s+/);
  const seed = await buildSeed({
    adminAuthProviderId,
    adminEmail,
    adminFirstName: first || "Daycare",
    adminLastName: rest.join(" "),
    now: new Date(),
  });

  const outFile = resolve(arg("out") || DEFAULT_OUT);
  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, `-- Generated by scripts/seed/seed.ts — development sample data only.\n${seed.statements.join("\n")}\n`);
  console.log(`Wrote ${seed.statements.length} statements to ${outFile}`);

  if (arg("out") !== undefined) return;
  if (!existsSync(join(WORKER_DIR, "node_modules"))) fail("Install the gateway Worker first: npm --prefix cloudflare/d1-gateway install");

  const wranglerArgs = ["wrangler", "d1", "execute", "DB", `--${target}`, `--file=${outFile}`];
  console.log(`Running: npx ${wranglerArgs.join(" ")}  (in cloudflare/d1-gateway)`);
  // shell is required to resolve npx on Windows, and cmd.exe splits unquoted paths.
  const spawnArgs = process.platform === "win32" ? wranglerArgs.map(quoteWindowsArg) : wranglerArgs;
  execFileSync(process.platform === "win32" ? "npx.cmd" : "npx", spawnArgs, {
    cwd: WORKER_DIR,
    stdio: "inherit",
    shell: process.platform === "win32",
  });

  console.log("\n✔ Seed complete");
  console.table(seed.summary);
  console.log("Demo time-clock PINs (development only):");
  console.table(seed.demoPins);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
